### ISSUE TITLE
Feature: User can view a list of Pokemon

### ISSUE THREAD

**Issue by aehrenkranz** [aehrenkranz/My-Pokedex#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view a list of all current Pokemon sorted by their Pokedex number.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will see a list of x number of Pokemon (depending on what size screen they have) that they can scroll through. The name and Pokedex number will be visible on this list. Current selection will be highlighted

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![mobile](https://github.com/aehrenkranz/ajax-project/assets/130402253/57e91de3-5fff-48fc-b174-2069f9a6f61c)
![desktop](https://github.com/aehrenkranz/ajax-project/assets/130402253/4bedaa64-e54c-4080-b69c-fa2849bb4615)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML skeleton
- [x] Add IMG element for this specific module
- [x] Add CSS for styling
- [x] Create listeners for when different entry is clicked (target needs to be highlighted with class change)
- [x] Add classes to the appropriate elements to highlight an entry when necessary
- [x] Test with fake list elements first to make sure scrolling works as intended
- [x] Make GET request for the full list of Pokemon
- [x] Add JS to create a list element for each Pokemon
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
