### ISSUE TITLE
Feature: User can filter by name

### ISSUE THREAD

**Issue by aehrenkranz** [aehrenkranz/My-Pokedex#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
To filter through the list of Pokemon by name (or part of name)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will type in a string into the search bar, and code will adjust the results accordingly.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add HTML elements for search bar
- [x] Add styling to elements
- [x] Add conditional logic to hide entries that don't contain the provided string
- [x] Test functionality
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
